### ISSUE TITLE
[Join Request] Idum (The 9th Age staff - Essence of war)

### ISSUE THREAD

**Issue by OgreSage** [BSData/the-9th-age-essence-of-war#3]
Hello,

I'm Idum from the Essence of War team (EoW); as the current repository is outdated, we decided to internalize within the team the maintenance of the BS data.

I could not get reply from rzmoz through the forum so far, so it would be easier that I get direct write access to authorize the pull request I initiated some weeks ago.

BR,
Idum

**Comment by Mad-Spy** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/4779405732)
:robot: Invited @OgreSage with **push** access. Invite can be accepted on https://github.com/BSData/the-9th-age-essence-of-war/invitations
